version: "2"

services:

  zookeeper-01:
    image: gsengun/zookeeper:3.5.0-alpha
    volumes:
      - ./Zookeeper/zoo.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.cfg:ro
      - ./Zookeeper/zoo.dynamic.1.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.dynamic.cfg
      - ./Zookeeper/1.id:/opt/zookeeper-3.5.0-alpha/data/myid:ro

  zookeeper-02:
    image: gsengun/zookeeper:3.5.0-alpha
    volumes:
      - ./Zookeeper/zoo.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.cfg:ro
      - ./Zookeeper/zoo.dynamic.2.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.dynamic.cfg
      - ./Zookeeper/2.id:/opt/zookeeper-3.5.0-alpha/data/myid:ro

  zookeeper-03:
    image: gsengun/zookeeper:3.5.0-alpha
    volumes:
      - ./Zookeeper/zoo.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.cfg:ro
      - ./Zookeeper/zoo.dynamic.3.cfg:/opt/zookeeper-3.5.0-alpha/conf/zoo.dynamic.cfg
      - ./Zookeeper/3.id:/opt/zookeeper-3.5.0-alpha/data/myid:ro

  kafka-01:
    image: gsengun/kafka:0.10.1.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-01
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1

  kafka-02:
    image: gsengun/kafka:0.10.1.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-02
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=2

  kafka-03:
    image: gsengun/kafka:0.10.1.0
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-03
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=3

  kafka-cat:
    image: ryane/kafkacat

